// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v1alpha1 "open-cluster-management.io/api/addon/v1alpha1"
	scheme "open-cluster-management.io/api/client/addon/clientset/versioned/scheme"
)

// AddOnHubConfigsGetter has a method to return a AddOnHubConfigInterface.
// A group's client should implement this interface.
type AddOnHubConfigsGetter interface {
	AddOnHubConfigs() AddOnHubConfigInterface
}

// AddOnHubConfigInterface has methods to work with AddOnHubConfig resources.
type AddOnHubConfigInterface interface {
	Create(ctx context.Context, addOnHubConfig *v1alpha1.AddOnHubConfig, opts v1.CreateOptions) (*v1alpha1.AddOnHubConfig, error)
	Update(ctx context.Context, addOnHubConfig *v1alpha1.AddOnHubConfig, opts v1.UpdateOptions) (*v1alpha1.AddOnHubConfig, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.AddOnHubConfig, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.AddOnHubConfigList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.AddOnHubConfig, err error)
	AddOnHubConfigExpansion
}

// addOnHubConfigs implements AddOnHubConfigInterface
type addOnHubConfigs struct {
	client rest.Interface
}

// newAddOnHubConfigs returns a AddOnHubConfigs
func newAddOnHubConfigs(c *AddonV1alpha1Client) *addOnHubConfigs {
	return &addOnHubConfigs{
		client: c.RESTClient(),
	}
}

// Get takes name of the addOnHubConfig, and returns the corresponding addOnHubConfig object, and an error if there is any.
func (c *addOnHubConfigs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.AddOnHubConfig, err error) {
	result = &v1alpha1.AddOnHubConfig{}
	err = c.client.Get().
		Resource("addonhubconfigs").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of AddOnHubConfigs that match those selectors.
func (c *addOnHubConfigs) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.AddOnHubConfigList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.AddOnHubConfigList{}
	err = c.client.Get().
		Resource("addonhubconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested addOnHubConfigs.
func (c *addOnHubConfigs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("addonhubconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a addOnHubConfig and creates it.  Returns the server's representation of the addOnHubConfig, and an error, if there is any.
func (c *addOnHubConfigs) Create(ctx context.Context, addOnHubConfig *v1alpha1.AddOnHubConfig, opts v1.CreateOptions) (result *v1alpha1.AddOnHubConfig, err error) {
	result = &v1alpha1.AddOnHubConfig{}
	err = c.client.Post().
		Resource("addonhubconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(addOnHubConfig).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a addOnHubConfig and updates it. Returns the server's representation of the addOnHubConfig, and an error, if there is any.
func (c *addOnHubConfigs) Update(ctx context.Context, addOnHubConfig *v1alpha1.AddOnHubConfig, opts v1.UpdateOptions) (result *v1alpha1.AddOnHubConfig, err error) {
	result = &v1alpha1.AddOnHubConfig{}
	err = c.client.Put().
		Resource("addonhubconfigs").
		Name(addOnHubConfig.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(addOnHubConfig).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the addOnHubConfig and deletes it. Returns an error if one occurs.
func (c *addOnHubConfigs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("addonhubconfigs").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *addOnHubConfigs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("addonhubconfigs").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched addOnHubConfig.
func (c *addOnHubConfigs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.AddOnHubConfig, err error) {
	result = &v1alpha1.AddOnHubConfig{}
	err = c.client.Patch(pt).
		Resource("addonhubconfigs").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
