// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
	v1alpha1 "open-cluster-management.io/api/addon/v1alpha1"
	scheme "open-cluster-management.io/api/client/addon/clientset/versioned/scheme"
)

// AddOnDeploymentConfigsGetter has a method to return a AddOnDeploymentConfigInterface.
// A group's client should implement this interface.
type AddOnDeploymentConfigsGetter interface {
	AddOnDeploymentConfigs(namespace string) AddOnDeploymentConfigInterface
}

// AddOnDeploymentConfigInterface has methods to work with AddOnDeploymentConfig resources.
type AddOnDeploymentConfigInterface interface {
	Create(ctx context.Context, addOnDeploymentConfig *v1alpha1.AddOnDeploymentConfig, opts v1.CreateOptions) (*v1alpha1.AddOnDeploymentConfig, error)
	Update(ctx context.Context, addOnDeploymentConfig *v1alpha1.AddOnDeploymentConfig, opts v1.UpdateOptions) (*v1alpha1.AddOnDeploymentConfig, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.AddOnDeploymentConfig, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.AddOnDeploymentConfigList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.AddOnDeploymentConfig, err error)
	AddOnDeploymentConfigExpansion
}

// addOnDeploymentConfigs implements AddOnDeploymentConfigInterface
type addOnDeploymentConfigs struct {
	*gentype.ClientWithList[*v1alpha1.AddOnDeploymentConfig, *v1alpha1.AddOnDeploymentConfigList]
}

// newAddOnDeploymentConfigs returns a AddOnDeploymentConfigs
func newAddOnDeploymentConfigs(c *AddonV1alpha1Client, namespace string) *addOnDeploymentConfigs {
	return &addOnDeploymentConfigs{
		gentype.NewClientWithList[*v1alpha1.AddOnDeploymentConfig, *v1alpha1.AddOnDeploymentConfigList](
			"addondeploymentconfigs",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *v1alpha1.AddOnDeploymentConfig { return &v1alpha1.AddOnDeploymentConfig{} },
			func() *v1alpha1.AddOnDeploymentConfigList { return &v1alpha1.AddOnDeploymentConfigList{} }),
	}
}
