// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

type AddOnDeploymentConfigExpansion interface{}

type AddOnHubConfigExpansion interface{}

type ClusterManagementAddOnExpansion interface{}

type ManagedClusterAddOnExpansion interface{}
