package v1alpha1

// This file contains a collection of methods that can be used from go-restful to
// generate Swagger API documentation for its models. Please read this PR for more
// information on the implementation: https://github.com/emicklei/go-restful/pull/215
//
// TODOs are ignored from the parser (e.g. TODO(andronat):... || TODO:...) if and only if
// they are on one line! For multiple line or blocks that you want to ignore use ---.
// Any context after a --- is ignored.
//
// Those methods can be generated by using hack/update-swagger-docs.sh

// AUTO-GENERATED FUNCTIONS START HERE
var map_LocalPlacementReference = map[string]string{
	"":     "localPlacementReference is the name of a Placement resource in current namespace",
	"name": "Name of the Placement resource in the current namespace",
}

func (LocalPlacementReference) SwaggerDoc() map[string]string {
	return map_LocalPlacementReference
}

var map_PlaceManifestWork = map[string]string{
	"":       "PlaceManifestWork is the Schema for the PlaceManifestWorks API. This custom resource is able to apply ManifestWork using Placement for 0..n ManagedCluster(in their namespaces). It will also remove the ManifestWork custom resources when deleted. Lastly the specific ManifestWork custom resources created per ManagedCluster namespace will be adjusted based on PlacementDecision changes.",
	"spec":   "Spec reperesents the desired ManifestWork payload and Placement reference to be reconciled",
	"status": "Status represent the current status of Placing ManifestWork resources",
}

func (PlaceManifestWork) SwaggerDoc() map[string]string {
	return map_PlaceManifestWork
}

var map_PlaceManifestWorkList = map[string]string{
	"": "\n\nPlaceManifestWorkList contains a list of PlaceManifestWork",
}

func (PlaceManifestWorkList) SwaggerDoc() map[string]string {
	return map_PlaceManifestWorkList
}

var map_PlaceManifestWorkSpec = map[string]string{
	"":                     "PlaceManifestWorkSpec defines the desired state of PlaceManifestWork",
	"manifestWorkTemplate": "ManifestWorkSpec is the ManifestWorkSpec that will be used to generate a per-cluster ManifestWork",
	"placementRef":         "PacementRef is the name of the Placement resource, from which a PlacementDecision will be found and used to distribute the ManifestWork",
}

func (PlaceManifestWorkSpec) SwaggerDoc() map[string]string {
	return map_PlaceManifestWorkSpec
}

var map_PlaceManifestWorkStatus = map[string]string{
	"":                   "PlaceManifestWorkStatus defines the observed state of PlaceManifestWork",
	"conditions":         "Conditions contains the different condition statuses for distrbution of ManifestWork resources Valid condition types are: 1. AppliedManifestWorks represents ManifestWorks have been distributed as per placement All, Partial, None, Problem 2. PlacementRefValid",
	"placedManifestWork": "ManifestWorkDelivery tracks each ManifestWork that was created, including that it was applied and its overall status",
	"summary":            "Summary that reflects all relevant ManifestWorks",
}

func (PlaceManifestWorkStatus) SwaggerDoc() map[string]string {
	return map_PlaceManifestWorkStatus
}

var map_PlacedManifestWork = map[string]string{
	"workRef":   "Work is an objectReference to the actual ManifestWork resource",
	"timestamp": "Timestamp is the time when the ManifestWork was last modified",
}

func (PlacedManifestWork) SwaggerDoc() map[string]string {
	return map_PlacedManifestWork
}

// AUTO-GENERATED FUNCTIONS END HERE
