//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalPlacementReference) DeepCopyInto(out *LocalPlacementReference) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalPlacementReference.
func (in *LocalPlacementReference) DeepCopy() *LocalPlacementReference {
	if in == nil {
		return nil
	}
	out := new(LocalPlacementReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlaceManifestWork) DeepCopyInto(out *PlaceManifestWork) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlaceManifestWork.
func (in *PlaceManifestWork) DeepCopy() *PlaceManifestWork {
	if in == nil {
		return nil
	}
	out := new(PlaceManifestWork)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlaceManifestWorkList) DeepCopyInto(out *PlaceManifestWorkList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PlaceManifestWork, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlaceManifestWorkList.
func (in *PlaceManifestWorkList) DeepCopy() *PlaceManifestWorkList {
	if in == nil {
		return nil
	}
	out := new(PlaceManifestWorkList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlaceManifestWorkSpec) DeepCopyInto(out *PlaceManifestWorkSpec) {
	*out = *in
<<<<<<< HEAD:place-work/v1alpha1/zz_generated.deepcopy.go
	in.ManifestWorkSpec.DeepCopyInto(&out.ManifestWorkSpec)
	if in.PlacementRef != nil {
		in, out := &in.PlacementRef, &out.PlacementRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
=======
	in.ManifestWorkTemplate.DeepCopyInto(&out.ManifestWorkTemplate)
	out.PlacementRef = in.PlacementRef
>>>>>>> 4ececc5... Apply PR comments:work/v1alpha1/zz_generated.deepcopy.go
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlaceManifestWorkSpec.
func (in *PlaceManifestWorkSpec) DeepCopy() *PlaceManifestWorkSpec {
	if in == nil {
		return nil
	}
	out := new(PlaceManifestWorkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlaceManifestWorkStatus) DeepCopyInto(out *PlaceManifestWorkStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PlacedManifestWork != nil {
		in, out := &in.PlacedManifestWork, &out.PlacedManifestWork
		*out = make([]PlacedManifestWork, len(*in))
		copy(*out, *in)
	}
	if in.PlacedManifestWorkSummary != nil {
		in, out := &in.PlacedManifestWorkSummary, &out.PlacedManifestWorkSummary
		*out = make([]PlacedManifestWorkSummary, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlaceManifestWorkStatus.
func (in *PlaceManifestWorkStatus) DeepCopy() *PlaceManifestWorkStatus {
	if in == nil {
		return nil
	}
	out := new(PlaceManifestWorkStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlacedManifestWork) DeepCopyInto(out *PlacedManifestWork) {
	*out = *in
	out.Work = in.Work
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlacedManifestWork.
func (in *PlacedManifestWork) DeepCopy() *PlacedManifestWork {
	if in == nil {
		return nil
	}
	out := new(PlacedManifestWork)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlacedManifestWorkSummary) DeepCopyInto(out *PlacedManifestWorkSummary) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlacedManifestWorkSummary.
func (in *PlacedManifestWorkSummary) DeepCopy() *PlacedManifestWorkSummary {
	if in == nil {
		return nil
	}
	out := new(PlacedManifestWorkSummary)
	in.DeepCopyInto(out)
	return out
}
