//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalPlacementReference) DeepCopyInto(out *LocalPlacementReference) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalPlacementReference.
func (in *LocalPlacementReference) DeepCopy() *LocalPlacementReference {
	if in == nil {
		return nil
	}
	out := new(LocalPlacementReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManifestWorkSet) DeepCopyInto(out *ManifestWorkSet) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManifestWorkSet.
func (in *ManifestWorkSet) DeepCopy() *ManifestWorkSet {
	if in == nil {
		return nil
	}
	out := new(ManifestWorkSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ManifestWorkSet) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManifestWorkSetList) DeepCopyInto(out *ManifestWorkSetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ManifestWorkSet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManifestWorkSetList.
func (in *ManifestWorkSetList) DeepCopy() *ManifestWorkSetList {
	if in == nil {
		return nil
	}
	out := new(ManifestWorkSetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ManifestWorkSetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManifestWorkSetSpec) DeepCopyInto(out *ManifestWorkSetSpec) {
	*out = *in
	in.ManifestWorkTemplate.DeepCopyInto(&out.ManifestWorkTemplate)
	if in.PlacementRefs != nil {
		in, out := &in.PlacementRefs, &out.PlacementRefs
		*out = make([]LocalPlacementReference, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManifestWorkSetSpec.
func (in *ManifestWorkSetSpec) DeepCopy() *ManifestWorkSetSpec {
	if in == nil {
		return nil
	}
	out := new(ManifestWorkSetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManifestWorkSetStatus) DeepCopyInto(out *ManifestWorkSetStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.Summary = in.Summary
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManifestWorkSetStatus.
func (in *ManifestWorkSetStatus) DeepCopy() *ManifestWorkSetStatus {
	if in == nil {
		return nil
	}
	out := new(ManifestWorkSetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManifestWorkSetSummary) DeepCopyInto(out *ManifestWorkSetSummary) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManifestWorkSetSummary.
func (in *ManifestWorkSetSummary) DeepCopy() *ManifestWorkSetSummary {
	if in == nil {
		return nil
	}
	out := new(ManifestWorkSetSummary)
	in.DeepCopyInto(out)
	return out
}
