// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	internalinterfaces "github.com/open-cluster-management/api/client/cluster/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// ManagedClusterClaims returns a ManagedClusterClaimInformer.
	ManagedClusterClaims() ManagedClusterClaimInformer
	// MirroredManagedClusters returns a MirroredManagedClusterInformer.
	MirroredManagedClusters() MirroredManagedClusterInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// ManagedClusterClaims returns a ManagedClusterClaimInformer.
func (v *version) ManagedClusterClaims() ManagedClusterClaimInformer {
	return &managedClusterClaimInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// MirroredManagedClusters returns a MirroredManagedClusterInformer.
func (v *version) MirroredManagedClusters() MirroredManagedClusterInformer {
	return &mirroredManagedClusterInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
