// Code generated by client-gen. DO NOT EDIT.

package v1beta2

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
	scheme "open-cluster-management.io/api/client/cluster/clientset/versioned/scheme"
	v1beta2 "open-cluster-management.io/api/cluster/v1beta2"
)

// ManagedClusterSetBindingsGetter has a method to return a ManagedClusterSetBindingInterface.
// A group's client should implement this interface.
type ManagedClusterSetBindingsGetter interface {
	ManagedClusterSetBindings(namespace string) ManagedClusterSetBindingInterface
}

// ManagedClusterSetBindingInterface has methods to work with ManagedClusterSetBinding resources.
type ManagedClusterSetBindingInterface interface {
	Create(ctx context.Context, managedClusterSetBinding *v1beta2.ManagedClusterSetBinding, opts v1.CreateOptions) (*v1beta2.ManagedClusterSetBinding, error)
	Update(ctx context.Context, managedClusterSetBinding *v1beta2.ManagedClusterSetBinding, opts v1.UpdateOptions) (*v1beta2.ManagedClusterSetBinding, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, managedClusterSetBinding *v1beta2.ManagedClusterSetBinding, opts v1.UpdateOptions) (*v1beta2.ManagedClusterSetBinding, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1beta2.ManagedClusterSetBinding, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1beta2.ManagedClusterSetBindingList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta2.ManagedClusterSetBinding, err error)
	ManagedClusterSetBindingExpansion
}

// managedClusterSetBindings implements ManagedClusterSetBindingInterface
type managedClusterSetBindings struct {
	*gentype.ClientWithList[*v1beta2.ManagedClusterSetBinding, *v1beta2.ManagedClusterSetBindingList]
}

// newManagedClusterSetBindings returns a ManagedClusterSetBindings
func newManagedClusterSetBindings(c *ClusterV1beta2Client, namespace string) *managedClusterSetBindings {
	return &managedClusterSetBindings{
		gentype.NewClientWithList[*v1beta2.ManagedClusterSetBinding, *v1beta2.ManagedClusterSetBindingList](
			"managedclustersetbindings",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *v1beta2.ManagedClusterSetBinding { return &v1beta2.ManagedClusterSetBinding{} },
			func() *v1beta2.ManagedClusterSetBindingList { return &v1beta2.ManagedClusterSetBindingList{} }),
	}
}
