// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
	v1alpha1 "open-cluster-management.io/api/addon/v1alpha1"
)

// AddOnHubConfigLister helps list AddOnHubConfigs.
// All objects returned here must be treated as read-only.
type AddOnHubConfigLister interface {
	// List lists all AddOnHubConfigs in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.AddOnHubConfig, err error)
	// Get retrieves the AddOnHubConfig from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.AddOnHubConfig, error)
	AddOnHubConfigListerExpansion
}

// addOnHubConfigLister implements the AddOnHubConfigLister interface.
type addOnHubConfigLister struct {
	indexer cache.Indexer
}

// NewAddOnHubConfigLister returns a new AddOnHubConfigLister.
func NewAddOnHubConfigLister(indexer cache.Indexer) AddOnHubConfigLister {
	return &addOnHubConfigLister{indexer: indexer}
}

// List lists all AddOnHubConfigs in the indexer.
func (s *addOnHubConfigLister) List(selector labels.Selector) (ret []*v1alpha1.AddOnHubConfig, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.AddOnHubConfig))
	})
	return ret, err
}

// Get retrieves the AddOnHubConfig from the index for a given name.
func (s *addOnHubConfigLister) Get(name string) (*v1alpha1.AddOnHubConfig, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("addonhubconfig"), name)
	}
	return obj.(*v1alpha1.AddOnHubConfig), nil
}
