// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// AddOnDeploymentConfigListerExpansion allows custom methods to be added to
// AddOnDeploymentConfigLister.
type AddOnDeploymentConfigListerExpansion interface{}

// ClusterManagementAddOnListerExpansion allows custom methods to be added to
// ClusterManagementAddOnLister.
type ClusterManagementAddOnListerExpansion interface{}

// ManagedClusterAddOnListerExpansion allows custom methods to be added to
// ManagedClusterAddOnLister.
type ManagedClusterAddOnListerExpansion interface{}

// ManagedClusterAddOnNamespaceListerExpansion allows custom methods to be added to
// ManagedClusterAddOnNamespaceLister.
type ManagedClusterAddOnNamespaceListerExpansion interface{}
