// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
	scheme "open-cluster-management.io/api/client/cluster/clientset/versioned/scheme"
	v1beta1 "open-cluster-management.io/api/cluster/v1beta1"
)

// PlacementDecisionsGetter has a method to return a PlacementDecisionInterface.
// A group's client should implement this interface.
type PlacementDecisionsGetter interface {
	PlacementDecisions(namespace string) PlacementDecisionInterface
}

// PlacementDecisionInterface has methods to work with PlacementDecision resources.
type PlacementDecisionInterface interface {
	Create(ctx context.Context, placementDecision *v1beta1.PlacementDecision, opts v1.CreateOptions) (*v1beta1.PlacementDecision, error)
	Update(ctx context.Context, placementDecision *v1beta1.PlacementDecision, opts v1.UpdateOptions) (*v1beta1.PlacementDecision, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, placementDecision *v1beta1.PlacementDecision, opts v1.UpdateOptions) (*v1beta1.PlacementDecision, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1beta1.PlacementDecision, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1beta1.PlacementDecisionList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.PlacementDecision, err error)
	PlacementDecisionExpansion
}

// placementDecisions implements PlacementDecisionInterface
type placementDecisions struct {
	*gentype.ClientWithList[*v1beta1.PlacementDecision, *v1beta1.PlacementDecisionList]
}

// newPlacementDecisions returns a PlacementDecisions
func newPlacementDecisions(c *ClusterV1beta1Client, namespace string) *placementDecisions {
	return &placementDecisions{
		gentype.NewClientWithList[*v1beta1.PlacementDecision, *v1beta1.PlacementDecisionList](
			"placementdecisions",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *v1beta1.PlacementDecision { return &v1beta1.PlacementDecision{} },
			func() *v1beta1.PlacementDecisionList { return &v1beta1.PlacementDecisionList{} }),
	}
}
