// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/listers"
	"k8s.io/client-go/tools/cache"
	v1 "open-cluster-management.io/api/operator/v1"
)

// ClusterManagerLister helps list ClusterManagers.
// All objects returned here must be treated as read-only.
type ClusterManagerLister interface {
	// List lists all ClusterManagers in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.ClusterManager, err error)
	// Get retrieves the ClusterManager from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1.ClusterManager, error)
	ClusterManagerListerExpansion
}

// clusterManagerLister implements the ClusterManagerLister interface.
type clusterManagerLister struct {
	listers.ResourceIndexer[*v1.ClusterManager]
}

// NewClusterManagerLister returns a new ClusterManagerLister.
func NewClusterManagerLister(indexer cache.Indexer) ClusterManagerLister {
	return &clusterManagerLister{listers.New[*v1.ClusterManager](indexer, v1.Resource("clustermanager"))}
}
