// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
	scheme "open-cluster-management.io/api/client/cluster/clientset/versioned/scheme"
	v1alpha1 "open-cluster-management.io/api/cluster/v1alpha1"
)

// AddOnPlacementScoresGetter has a method to return a AddOnPlacementScoreInterface.
// A group's client should implement this interface.
type AddOnPlacementScoresGetter interface {
	AddOnPlacementScores(namespace string) AddOnPlacementScoreInterface
}

// AddOnPlacementScoreInterface has methods to work with AddOnPlacementScore resources.
type AddOnPlacementScoreInterface interface {
	Create(ctx context.Context, addOnPlacementScore *v1alpha1.AddOnPlacementScore, opts v1.CreateOptions) (*v1alpha1.AddOnPlacementScore, error)
	Update(ctx context.Context, addOnPlacementScore *v1alpha1.AddOnPlacementScore, opts v1.UpdateOptions) (*v1alpha1.AddOnPlacementScore, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, addOnPlacementScore *v1alpha1.AddOnPlacementScore, opts v1.UpdateOptions) (*v1alpha1.AddOnPlacementScore, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.AddOnPlacementScore, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.AddOnPlacementScoreList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.AddOnPlacementScore, err error)
	AddOnPlacementScoreExpansion
}

// addOnPlacementScores implements AddOnPlacementScoreInterface
type addOnPlacementScores struct {
	*gentype.ClientWithList[*v1alpha1.AddOnPlacementScore, *v1alpha1.AddOnPlacementScoreList]
}

// newAddOnPlacementScores returns a AddOnPlacementScores
func newAddOnPlacementScores(c *ClusterV1alpha1Client, namespace string) *addOnPlacementScores {
	return &addOnPlacementScores{
		gentype.NewClientWithList[*v1alpha1.AddOnPlacementScore, *v1alpha1.AddOnPlacementScoreList](
			"addonplacementscores",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *v1alpha1.AddOnPlacementScore { return &v1alpha1.AddOnPlacementScore{} },
			func() *v1alpha1.AddOnPlacementScoreList { return &v1alpha1.AddOnPlacementScoreList{} }),
	}
}
