// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
	scheme "open-cluster-management.io/api/client/cluster/clientset/versioned/scheme"
	v1alpha1 "open-cluster-management.io/api/cluster/v1alpha1"
)

// ClusterClaimsGetter has a method to return a ClusterClaimInterface.
// A group's client should implement this interface.
type ClusterClaimsGetter interface {
	ClusterClaims() ClusterClaimInterface
}

// ClusterClaimInterface has methods to work with ClusterClaim resources.
type ClusterClaimInterface interface {
	Create(ctx context.Context, clusterClaim *v1alpha1.ClusterClaim, opts v1.CreateOptions) (*v1alpha1.ClusterClaim, error)
	Update(ctx context.Context, clusterClaim *v1alpha1.ClusterClaim, opts v1.UpdateOptions) (*v1alpha1.ClusterClaim, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.ClusterClaim, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.ClusterClaimList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ClusterClaim, err error)
	ClusterClaimExpansion
}

// clusterClaims implements ClusterClaimInterface
type clusterClaims struct {
	*gentype.ClientWithList[*v1alpha1.ClusterClaim, *v1alpha1.ClusterClaimList]
}

// newClusterClaims returns a ClusterClaims
func newClusterClaims(c *ClusterV1alpha1Client) *clusterClaims {
	return &clusterClaims{
		gentype.NewClientWithList[*v1alpha1.ClusterClaim, *v1alpha1.ClusterClaimList](
			"clusterclaims",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *v1alpha1.ClusterClaim { return &v1alpha1.ClusterClaim{} },
			func() *v1alpha1.ClusterClaimList { return &v1alpha1.ClusterClaimList{} }),
	}
}
