// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	scheme "github.com/open-cluster-management/api/client/cluster/clientset/versioned/scheme"
	v1alpha1 "github.com/open-cluster-management/api/cluster/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ManagedClusterClaimsGetter has a method to return a ManagedClusterClaimInterface.
// A group's client should implement this interface.
type ManagedClusterClaimsGetter interface {
	ManagedClusterClaims(namespace string) ManagedClusterClaimInterface
}

// ManagedClusterClaimInterface has methods to work with ManagedClusterClaim resources.
type ManagedClusterClaimInterface interface {
	Create(ctx context.Context, managedClusterClaim *v1alpha1.ManagedClusterClaim, opts v1.CreateOptions) (*v1alpha1.ManagedClusterClaim, error)
	Update(ctx context.Context, managedClusterClaim *v1alpha1.ManagedClusterClaim, opts v1.UpdateOptions) (*v1alpha1.ManagedClusterClaim, error)
	UpdateStatus(ctx context.Context, managedClusterClaim *v1alpha1.ManagedClusterClaim, opts v1.UpdateOptions) (*v1alpha1.ManagedClusterClaim, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.ManagedClusterClaim, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.ManagedClusterClaimList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ManagedClusterClaim, err error)
	ManagedClusterClaimExpansion
}

// managedClusterClaims implements ManagedClusterClaimInterface
type managedClusterClaims struct {
	client rest.Interface
	ns     string
}

// newManagedClusterClaims returns a ManagedClusterClaims
func newManagedClusterClaims(c *ClusterV1alpha1Client, namespace string) *managedClusterClaims {
	return &managedClusterClaims{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the managedClusterClaim, and returns the corresponding managedClusterClaim object, and an error if there is any.
func (c *managedClusterClaims) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ManagedClusterClaim, err error) {
	result = &v1alpha1.ManagedClusterClaim{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("managedclusterclaims").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ManagedClusterClaims that match those selectors.
func (c *managedClusterClaims) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ManagedClusterClaimList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.ManagedClusterClaimList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("managedclusterclaims").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested managedClusterClaims.
func (c *managedClusterClaims) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("managedclusterclaims").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a managedClusterClaim and creates it.  Returns the server's representation of the managedClusterClaim, and an error, if there is any.
func (c *managedClusterClaims) Create(ctx context.Context, managedClusterClaim *v1alpha1.ManagedClusterClaim, opts v1.CreateOptions) (result *v1alpha1.ManagedClusterClaim, err error) {
	result = &v1alpha1.ManagedClusterClaim{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("managedclusterclaims").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(managedClusterClaim).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a managedClusterClaim and updates it. Returns the server's representation of the managedClusterClaim, and an error, if there is any.
func (c *managedClusterClaims) Update(ctx context.Context, managedClusterClaim *v1alpha1.ManagedClusterClaim, opts v1.UpdateOptions) (result *v1alpha1.ManagedClusterClaim, err error) {
	result = &v1alpha1.ManagedClusterClaim{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("managedclusterclaims").
		Name(managedClusterClaim.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(managedClusterClaim).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *managedClusterClaims) UpdateStatus(ctx context.Context, managedClusterClaim *v1alpha1.ManagedClusterClaim, opts v1.UpdateOptions) (result *v1alpha1.ManagedClusterClaim, err error) {
	result = &v1alpha1.ManagedClusterClaim{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("managedclusterclaims").
		Name(managedClusterClaim.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(managedClusterClaim).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the managedClusterClaim and deletes it. Returns an error if one occurs.
func (c *managedClusterClaims) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("managedclusterclaims").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *managedClusterClaims) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("managedclusterclaims").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched managedClusterClaim.
func (c *managedClusterClaims) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ManagedClusterClaim, err error) {
	result = &v1alpha1.ManagedClusterClaim{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("managedclusterclaims").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
