// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	scheme "github.com/open-cluster-management/api/client/cluster/clientset/versioned/scheme"
	v1alpha1 "github.com/open-cluster-management/api/cluster/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// MirroredManagedClustersGetter has a method to return a MirroredManagedClusterInterface.
// A group's client should implement this interface.
type MirroredManagedClustersGetter interface {
	MirroredManagedClusters(namespace string) MirroredManagedClusterInterface
}

// MirroredManagedClusterInterface has methods to work with MirroredManagedCluster resources.
type MirroredManagedClusterInterface interface {
	Create(ctx context.Context, mirroredManagedCluster *v1alpha1.MirroredManagedCluster, opts v1.CreateOptions) (*v1alpha1.MirroredManagedCluster, error)
	Update(ctx context.Context, mirroredManagedCluster *v1alpha1.MirroredManagedCluster, opts v1.UpdateOptions) (*v1alpha1.MirroredManagedCluster, error)
	UpdateStatus(ctx context.Context, mirroredManagedCluster *v1alpha1.MirroredManagedCluster, opts v1.UpdateOptions) (*v1alpha1.MirroredManagedCluster, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.MirroredManagedCluster, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.MirroredManagedClusterList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.MirroredManagedCluster, err error)
	MirroredManagedClusterExpansion
}

// mirroredManagedClusters implements MirroredManagedClusterInterface
type mirroredManagedClusters struct {
	client rest.Interface
	ns     string
}

// newMirroredManagedClusters returns a MirroredManagedClusters
func newMirroredManagedClusters(c *ClusterV1alpha1Client, namespace string) *mirroredManagedClusters {
	return &mirroredManagedClusters{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the mirroredManagedCluster, and returns the corresponding mirroredManagedCluster object, and an error if there is any.
func (c *mirroredManagedClusters) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.MirroredManagedCluster, err error) {
	result = &v1alpha1.MirroredManagedCluster{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("mirroredmanagedclusters").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of MirroredManagedClusters that match those selectors.
func (c *mirroredManagedClusters) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.MirroredManagedClusterList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.MirroredManagedClusterList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("mirroredmanagedclusters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested mirroredManagedClusters.
func (c *mirroredManagedClusters) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("mirroredmanagedclusters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a mirroredManagedCluster and creates it.  Returns the server's representation of the mirroredManagedCluster, and an error, if there is any.
func (c *mirroredManagedClusters) Create(ctx context.Context, mirroredManagedCluster *v1alpha1.MirroredManagedCluster, opts v1.CreateOptions) (result *v1alpha1.MirroredManagedCluster, err error) {
	result = &v1alpha1.MirroredManagedCluster{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("mirroredmanagedclusters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(mirroredManagedCluster).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a mirroredManagedCluster and updates it. Returns the server's representation of the mirroredManagedCluster, and an error, if there is any.
func (c *mirroredManagedClusters) Update(ctx context.Context, mirroredManagedCluster *v1alpha1.MirroredManagedCluster, opts v1.UpdateOptions) (result *v1alpha1.MirroredManagedCluster, err error) {
	result = &v1alpha1.MirroredManagedCluster{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("mirroredmanagedclusters").
		Name(mirroredManagedCluster.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(mirroredManagedCluster).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *mirroredManagedClusters) UpdateStatus(ctx context.Context, mirroredManagedCluster *v1alpha1.MirroredManagedCluster, opts v1.UpdateOptions) (result *v1alpha1.MirroredManagedCluster, err error) {
	result = &v1alpha1.MirroredManagedCluster{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("mirroredmanagedclusters").
		Name(mirroredManagedCluster.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(mirroredManagedCluster).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the mirroredManagedCluster and deletes it. Returns an error if one occurs.
func (c *mirroredManagedClusters) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("mirroredmanagedclusters").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *mirroredManagedClusters) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("mirroredmanagedclusters").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched mirroredManagedCluster.
func (c *mirroredManagedClusters) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.MirroredManagedCluster, err error) {
	result = &v1alpha1.MirroredManagedCluster{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("mirroredmanagedclusters").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
