// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	addonv1alpha1 "open-cluster-management.io/api/addon/v1alpha1"
	versioned "open-cluster-management.io/api/client/addon/clientset/versioned"
	internalinterfaces "open-cluster-management.io/api/client/addon/informers/externalversions/internalinterfaces"
	v1alpha1 "open-cluster-management.io/api/client/addon/listers/addon/v1alpha1"
)

// AddOnHubConfigInformer provides access to a shared informer and lister for
// AddOnHubConfigs.
type AddOnHubConfigInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.AddOnHubConfigLister
}

type addOnHubConfigInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewAddOnHubConfigInformer constructs a new informer for AddOnHubConfig type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewAddOnHubConfigInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredAddOnHubConfigInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredAddOnHubConfigInformer constructs a new informer for AddOnHubConfig type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredAddOnHubConfigInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AddonV1alpha1().AddOnHubConfigs().List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AddonV1alpha1().AddOnHubConfigs().Watch(context.TODO(), options)
			},
		},
		&addonv1alpha1.AddOnHubConfig{},
		resyncPeriod,
		indexers,
	)
}

func (f *addOnHubConfigInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredAddOnHubConfigInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *addOnHubConfigInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&addonv1alpha1.AddOnHubConfig{}, f.defaultInformer)
}

func (f *addOnHubConfigInformer) Lister() v1alpha1.AddOnHubConfigLister {
	return v1alpha1.NewAddOnHubConfigLister(f.Informer().GetIndexer())
}
