// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
	scheme "open-cluster-management.io/api/client/work/clientset/versioned/scheme"
	v1alpha1 "open-cluster-management.io/api/work/v1alpha1"
)

// ManifestWorkReplicaSetsGetter has a method to return a ManifestWorkReplicaSetInterface.
// A group's client should implement this interface.
type ManifestWorkReplicaSetsGetter interface {
	ManifestWorkReplicaSets(namespace string) ManifestWorkReplicaSetInterface
}

// ManifestWorkReplicaSetInterface has methods to work with ManifestWorkReplicaSet resources.
type ManifestWorkReplicaSetInterface interface {
	Create(ctx context.Context, manifestWorkReplicaSet *v1alpha1.ManifestWorkReplicaSet, opts v1.CreateOptions) (*v1alpha1.ManifestWorkReplicaSet, error)
	Update(ctx context.Context, manifestWorkReplicaSet *v1alpha1.ManifestWorkReplicaSet, opts v1.UpdateOptions) (*v1alpha1.ManifestWorkReplicaSet, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, manifestWorkReplicaSet *v1alpha1.ManifestWorkReplicaSet, opts v1.UpdateOptions) (*v1alpha1.ManifestWorkReplicaSet, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.ManifestWorkReplicaSet, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.ManifestWorkReplicaSetList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ManifestWorkReplicaSet, err error)
	ManifestWorkReplicaSetExpansion
}

// manifestWorkReplicaSets implements ManifestWorkReplicaSetInterface
type manifestWorkReplicaSets struct {
	*gentype.ClientWithList[*v1alpha1.ManifestWorkReplicaSet, *v1alpha1.ManifestWorkReplicaSetList]
}

// newManifestWorkReplicaSets returns a ManifestWorkReplicaSets
func newManifestWorkReplicaSets(c *WorkV1alpha1Client, namespace string) *manifestWorkReplicaSets {
	return &manifestWorkReplicaSets{
		gentype.NewClientWithList[*v1alpha1.ManifestWorkReplicaSet, *v1alpha1.ManifestWorkReplicaSetList](
			"manifestworkreplicasets",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *v1alpha1.ManifestWorkReplicaSet { return &v1alpha1.ManifestWorkReplicaSet{} },
			func() *v1alpha1.ManifestWorkReplicaSetList { return &v1alpha1.ManifestWorkReplicaSetList{} }),
	}
}
