// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "open-cluster-management.io/api/addon/v1alpha1"
)

// FakeAddOnDeploymentConfigs implements AddOnDeploymentConfigInterface
type FakeAddOnDeploymentConfigs struct {
	Fake *FakeAddonV1alpha1
	ns   string
}

var addondeploymentconfigsResource = v1alpha1.SchemeGroupVersion.WithResource("addondeploymentconfigs")

var addondeploymentconfigsKind = v1alpha1.SchemeGroupVersion.WithKind("AddOnDeploymentConfig")

// Get takes name of the addOnDeploymentConfig, and returns the corresponding addOnDeploymentConfig object, and an error if there is any.
func (c *FakeAddOnDeploymentConfigs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.AddOnDeploymentConfig, err error) {
	emptyResult := &v1alpha1.AddOnDeploymentConfig{}
	obj, err := c.Fake.
		Invokes(testing.NewGetActionWithOptions(addondeploymentconfigsResource, c.ns, name, options), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.AddOnDeploymentConfig), err
}

// List takes label and field selectors, and returns the list of AddOnDeploymentConfigs that match those selectors.
func (c *FakeAddOnDeploymentConfigs) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.AddOnDeploymentConfigList, err error) {
	emptyResult := &v1alpha1.AddOnDeploymentConfigList{}
	obj, err := c.Fake.
		Invokes(testing.NewListActionWithOptions(addondeploymentconfigsResource, addondeploymentconfigsKind, c.ns, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.AddOnDeploymentConfigList{ListMeta: obj.(*v1alpha1.AddOnDeploymentConfigList).ListMeta}
	for _, item := range obj.(*v1alpha1.AddOnDeploymentConfigList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested addOnDeploymentConfigs.
func (c *FakeAddOnDeploymentConfigs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchActionWithOptions(addondeploymentconfigsResource, c.ns, opts))

}

// Create takes the representation of a addOnDeploymentConfig and creates it.  Returns the server's representation of the addOnDeploymentConfig, and an error, if there is any.
func (c *FakeAddOnDeploymentConfigs) Create(ctx context.Context, addOnDeploymentConfig *v1alpha1.AddOnDeploymentConfig, opts v1.CreateOptions) (result *v1alpha1.AddOnDeploymentConfig, err error) {
	emptyResult := &v1alpha1.AddOnDeploymentConfig{}
	obj, err := c.Fake.
		Invokes(testing.NewCreateActionWithOptions(addondeploymentconfigsResource, c.ns, addOnDeploymentConfig, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.AddOnDeploymentConfig), err
}

// Update takes the representation of a addOnDeploymentConfig and updates it. Returns the server's representation of the addOnDeploymentConfig, and an error, if there is any.
func (c *FakeAddOnDeploymentConfigs) Update(ctx context.Context, addOnDeploymentConfig *v1alpha1.AddOnDeploymentConfig, opts v1.UpdateOptions) (result *v1alpha1.AddOnDeploymentConfig, err error) {
	emptyResult := &v1alpha1.AddOnDeploymentConfig{}
	obj, err := c.Fake.
		Invokes(testing.NewUpdateActionWithOptions(addondeploymentconfigsResource, c.ns, addOnDeploymentConfig, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.AddOnDeploymentConfig), err
}

// Delete takes name of the addOnDeploymentConfig and deletes it. Returns an error if one occurs.
func (c *FakeAddOnDeploymentConfigs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(addondeploymentconfigsResource, c.ns, name, opts), &v1alpha1.AddOnDeploymentConfig{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAddOnDeploymentConfigs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionActionWithOptions(addondeploymentconfigsResource, c.ns, opts, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.AddOnDeploymentConfigList{})
	return err
}

// Patch applies the patch and returns the patched addOnDeploymentConfig.
func (c *FakeAddOnDeploymentConfigs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.AddOnDeploymentConfig, err error) {
	emptyResult := &v1alpha1.AddOnDeploymentConfig{}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceActionWithOptions(addondeploymentconfigsResource, c.ns, name, pt, data, opts, subresources...), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.AddOnDeploymentConfig), err
}
