// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "open-cluster-management.io/api/addon/v1alpha1"
)

// FakeAddOnHubConfigs implements AddOnHubConfigInterface
type FakeAddOnHubConfigs struct {
	Fake *FakeAddonV1alpha1
}

var addonhubconfigsResource = schema.GroupVersionResource{Group: "addon.open-cluster-management.io", Version: "v1alpha1", Resource: "addonhubconfigs"}

var addonhubconfigsKind = schema.GroupVersionKind{Group: "addon.open-cluster-management.io", Version: "v1alpha1", Kind: "AddOnHubConfig"}

// Get takes name of the addOnHubConfig, and returns the corresponding addOnHubConfig object, and an error if there is any.
func (c *FakeAddOnHubConfigs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.AddOnHubConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(addonhubconfigsResource, name), &v1alpha1.AddOnHubConfig{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AddOnHubConfig), err
}

// List takes label and field selectors, and returns the list of AddOnHubConfigs that match those selectors.
func (c *FakeAddOnHubConfigs) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.AddOnHubConfigList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(addonhubconfigsResource, addonhubconfigsKind, opts), &v1alpha1.AddOnHubConfigList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.AddOnHubConfigList{ListMeta: obj.(*v1alpha1.AddOnHubConfigList).ListMeta}
	for _, item := range obj.(*v1alpha1.AddOnHubConfigList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested addOnHubConfigs.
func (c *FakeAddOnHubConfigs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(addonhubconfigsResource, opts))
}

// Create takes the representation of a addOnHubConfig and creates it.  Returns the server's representation of the addOnHubConfig, and an error, if there is any.
func (c *FakeAddOnHubConfigs) Create(ctx context.Context, addOnHubConfig *v1alpha1.AddOnHubConfig, opts v1.CreateOptions) (result *v1alpha1.AddOnHubConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(addonhubconfigsResource, addOnHubConfig), &v1alpha1.AddOnHubConfig{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AddOnHubConfig), err
}

// Update takes the representation of a addOnHubConfig and updates it. Returns the server's representation of the addOnHubConfig, and an error, if there is any.
func (c *FakeAddOnHubConfigs) Update(ctx context.Context, addOnHubConfig *v1alpha1.AddOnHubConfig, opts v1.UpdateOptions) (result *v1alpha1.AddOnHubConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(addonhubconfigsResource, addOnHubConfig), &v1alpha1.AddOnHubConfig{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AddOnHubConfig), err
}

// Delete takes name of the addOnHubConfig and deletes it. Returns an error if one occurs.
func (c *FakeAddOnHubConfigs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(addonhubconfigsResource, name, opts), &v1alpha1.AddOnHubConfig{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAddOnHubConfigs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(addonhubconfigsResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.AddOnHubConfigList{})
	return err
}

// Patch applies the patch and returns the patched addOnHubConfig.
func (c *FakeAddOnHubConfigs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.AddOnHubConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(addonhubconfigsResource, name, pt, data, subresources...), &v1alpha1.AddOnHubConfig{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AddOnHubConfig), err
}
