// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/open-cluster-management/api/cluster/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeManagedClusterClaims implements ManagedClusterClaimInterface
type FakeManagedClusterClaims struct {
	Fake *FakeClusterV1alpha1
	ns   string
}

var managedclusterclaimsResource = schema.GroupVersionResource{Group: "cluster.open-cluster-management.io", Version: "v1alpha1", Resource: "managedclusterclaims"}

var managedclusterclaimsKind = schema.GroupVersionKind{Group: "cluster.open-cluster-management.io", Version: "v1alpha1", Kind: "ManagedClusterClaim"}

// Get takes name of the managedClusterClaim, and returns the corresponding managedClusterClaim object, and an error if there is any.
func (c *FakeManagedClusterClaims) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ManagedClusterClaim, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(managedclusterclaimsResource, c.ns, name), &v1alpha1.ManagedClusterClaim{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ManagedClusterClaim), err
}

// List takes label and field selectors, and returns the list of ManagedClusterClaims that match those selectors.
func (c *FakeManagedClusterClaims) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ManagedClusterClaimList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(managedclusterclaimsResource, managedclusterclaimsKind, c.ns, opts), &v1alpha1.ManagedClusterClaimList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ManagedClusterClaimList{ListMeta: obj.(*v1alpha1.ManagedClusterClaimList).ListMeta}
	for _, item := range obj.(*v1alpha1.ManagedClusterClaimList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested managedClusterClaims.
func (c *FakeManagedClusterClaims) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(managedclusterclaimsResource, c.ns, opts))

}

// Create takes the representation of a managedClusterClaim and creates it.  Returns the server's representation of the managedClusterClaim, and an error, if there is any.
func (c *FakeManagedClusterClaims) Create(ctx context.Context, managedClusterClaim *v1alpha1.ManagedClusterClaim, opts v1.CreateOptions) (result *v1alpha1.ManagedClusterClaim, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(managedclusterclaimsResource, c.ns, managedClusterClaim), &v1alpha1.ManagedClusterClaim{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ManagedClusterClaim), err
}

// Update takes the representation of a managedClusterClaim and updates it. Returns the server's representation of the managedClusterClaim, and an error, if there is any.
func (c *FakeManagedClusterClaims) Update(ctx context.Context, managedClusterClaim *v1alpha1.ManagedClusterClaim, opts v1.UpdateOptions) (result *v1alpha1.ManagedClusterClaim, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(managedclusterclaimsResource, c.ns, managedClusterClaim), &v1alpha1.ManagedClusterClaim{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ManagedClusterClaim), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeManagedClusterClaims) UpdateStatus(ctx context.Context, managedClusterClaim *v1alpha1.ManagedClusterClaim, opts v1.UpdateOptions) (*v1alpha1.ManagedClusterClaim, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(managedclusterclaimsResource, "status", c.ns, managedClusterClaim), &v1alpha1.ManagedClusterClaim{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ManagedClusterClaim), err
}

// Delete takes name of the managedClusterClaim and deletes it. Returns an error if one occurs.
func (c *FakeManagedClusterClaims) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(managedclusterclaimsResource, c.ns, name), &v1alpha1.ManagedClusterClaim{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeManagedClusterClaims) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(managedclusterclaimsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ManagedClusterClaimList{})
	return err
}

// Patch applies the patch and returns the patched managedClusterClaim.
func (c *FakeManagedClusterClaims) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ManagedClusterClaim, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(managedclusterclaimsResource, c.ns, name, pt, data, subresources...), &v1alpha1.ManagedClusterClaim{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ManagedClusterClaim), err
}
