// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/open-cluster-management/api/cluster/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeMirroredManagedClusters implements MirroredManagedClusterInterface
type FakeMirroredManagedClusters struct {
	Fake *FakeClusterV1alpha1
	ns   string
}

var mirroredmanagedclustersResource = schema.GroupVersionResource{Group: "cluster.open-cluster-management.io", Version: "v1alpha1", Resource: "mirroredmanagedclusters"}

var mirroredmanagedclustersKind = schema.GroupVersionKind{Group: "cluster.open-cluster-management.io", Version: "v1alpha1", Kind: "MirroredManagedCluster"}

// Get takes name of the mirroredManagedCluster, and returns the corresponding mirroredManagedCluster object, and an error if there is any.
func (c *FakeMirroredManagedClusters) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.MirroredManagedCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(mirroredmanagedclustersResource, c.ns, name), &v1alpha1.MirroredManagedCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MirroredManagedCluster), err
}

// List takes label and field selectors, and returns the list of MirroredManagedClusters that match those selectors.
func (c *FakeMirroredManagedClusters) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.MirroredManagedClusterList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(mirroredmanagedclustersResource, mirroredmanagedclustersKind, c.ns, opts), &v1alpha1.MirroredManagedClusterList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.MirroredManagedClusterList{ListMeta: obj.(*v1alpha1.MirroredManagedClusterList).ListMeta}
	for _, item := range obj.(*v1alpha1.MirroredManagedClusterList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested mirroredManagedClusters.
func (c *FakeMirroredManagedClusters) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(mirroredmanagedclustersResource, c.ns, opts))

}

// Create takes the representation of a mirroredManagedCluster and creates it.  Returns the server's representation of the mirroredManagedCluster, and an error, if there is any.
func (c *FakeMirroredManagedClusters) Create(ctx context.Context, mirroredManagedCluster *v1alpha1.MirroredManagedCluster, opts v1.CreateOptions) (result *v1alpha1.MirroredManagedCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(mirroredmanagedclustersResource, c.ns, mirroredManagedCluster), &v1alpha1.MirroredManagedCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MirroredManagedCluster), err
}

// Update takes the representation of a mirroredManagedCluster and updates it. Returns the server's representation of the mirroredManagedCluster, and an error, if there is any.
func (c *FakeMirroredManagedClusters) Update(ctx context.Context, mirroredManagedCluster *v1alpha1.MirroredManagedCluster, opts v1.UpdateOptions) (result *v1alpha1.MirroredManagedCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(mirroredmanagedclustersResource, c.ns, mirroredManagedCluster), &v1alpha1.MirroredManagedCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MirroredManagedCluster), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeMirroredManagedClusters) UpdateStatus(ctx context.Context, mirroredManagedCluster *v1alpha1.MirroredManagedCluster, opts v1.UpdateOptions) (*v1alpha1.MirroredManagedCluster, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(mirroredmanagedclustersResource, "status", c.ns, mirroredManagedCluster), &v1alpha1.MirroredManagedCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MirroredManagedCluster), err
}

// Delete takes name of the mirroredManagedCluster and deletes it. Returns an error if one occurs.
func (c *FakeMirroredManagedClusters) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(mirroredmanagedclustersResource, c.ns, name), &v1alpha1.MirroredManagedCluster{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeMirroredManagedClusters) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(mirroredmanagedclustersResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.MirroredManagedClusterList{})
	return err
}

// Patch applies the patch and returns the patched mirroredManagedCluster.
func (c *FakeMirroredManagedClusters) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.MirroredManagedCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(mirroredmanagedclustersResource, c.ns, name, pt, data, subresources...), &v1alpha1.MirroredManagedCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MirroredManagedCluster), err
}
