// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "open-cluster-management.io/api/cluster/v1alpha1"
)

// FakeManagedClusterScalars implements ManagedClusterScalarInterface
type FakeManagedClusterScalars struct {
	Fake *FakeClusterV1alpha1
	ns   string
}

var managedclusterscalarsResource = schema.GroupVersionResource{Group: "cluster.open-cluster-management.io", Version: "v1alpha1", Resource: "managedclusterscalars"}

var managedclusterscalarsKind = schema.GroupVersionKind{Group: "cluster.open-cluster-management.io", Version: "v1alpha1", Kind: "ManagedClusterScalar"}

// Get takes name of the managedClusterScalar, and returns the corresponding managedClusterScalar object, and an error if there is any.
func (c *FakeManagedClusterScalars) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ManagedClusterScalar, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(managedclusterscalarsResource, c.ns, name), &v1alpha1.ManagedClusterScalar{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ManagedClusterScalar), err
}

// List takes label and field selectors, and returns the list of ManagedClusterScalars that match those selectors.
func (c *FakeManagedClusterScalars) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ManagedClusterScalarList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(managedclusterscalarsResource, managedclusterscalarsKind, c.ns, opts), &v1alpha1.ManagedClusterScalarList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ManagedClusterScalarList{ListMeta: obj.(*v1alpha1.ManagedClusterScalarList).ListMeta}
	for _, item := range obj.(*v1alpha1.ManagedClusterScalarList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested managedClusterScalars.
func (c *FakeManagedClusterScalars) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(managedclusterscalarsResource, c.ns, opts))

}

// Create takes the representation of a managedClusterScalar and creates it.  Returns the server's representation of the managedClusterScalar, and an error, if there is any.
func (c *FakeManagedClusterScalars) Create(ctx context.Context, managedClusterScalar *v1alpha1.ManagedClusterScalar, opts v1.CreateOptions) (result *v1alpha1.ManagedClusterScalar, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(managedclusterscalarsResource, c.ns, managedClusterScalar), &v1alpha1.ManagedClusterScalar{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ManagedClusterScalar), err
}

// Update takes the representation of a managedClusterScalar and updates it. Returns the server's representation of the managedClusterScalar, and an error, if there is any.
func (c *FakeManagedClusterScalars) Update(ctx context.Context, managedClusterScalar *v1alpha1.ManagedClusterScalar, opts v1.UpdateOptions) (result *v1alpha1.ManagedClusterScalar, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(managedclusterscalarsResource, c.ns, managedClusterScalar), &v1alpha1.ManagedClusterScalar{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ManagedClusterScalar), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeManagedClusterScalars) UpdateStatus(ctx context.Context, managedClusterScalar *v1alpha1.ManagedClusterScalar, opts v1.UpdateOptions) (*v1alpha1.ManagedClusterScalar, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(managedclusterscalarsResource, "status", c.ns, managedClusterScalar), &v1alpha1.ManagedClusterScalar{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ManagedClusterScalar), err
}

// Delete takes name of the managedClusterScalar and deletes it. Returns an error if one occurs.
func (c *FakeManagedClusterScalars) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(managedclusterscalarsResource, c.ns, name), &v1alpha1.ManagedClusterScalar{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeManagedClusterScalars) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(managedclusterscalarsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ManagedClusterScalarList{})
	return err
}

// Patch applies the patch and returns the patched managedClusterScalar.
func (c *FakeManagedClusterScalars) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ManagedClusterScalar, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(managedclusterscalarsResource, c.ns, name, pt, data, subresources...), &v1alpha1.ManagedClusterScalar{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ManagedClusterScalar), err
}
