// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// ManifestWorkSetListerExpansion allows custom methods to be added to
// ManifestWorkSetLister.
type ManifestWorkSetListerExpansion interface{}

// ManifestWorkSetNamespaceListerExpansion allows custom methods to be added to
// ManifestWorkSetNamespaceLister.
type ManifestWorkSetNamespaceListerExpansion interface{}
