// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
	v1alpha1 "open-cluster-management.io/api/work/v1alpha1"
)

// ManifestWorkSetLister helps list ManifestWorkSets.
// All objects returned here must be treated as read-only.
type ManifestWorkSetLister interface {
	// List lists all ManifestWorkSets in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.ManifestWorkSet, err error)
	// ManifestWorkSets returns an object that can list and get ManifestWorkSets.
	ManifestWorkSets(namespace string) ManifestWorkSetNamespaceLister
	ManifestWorkSetListerExpansion
}

// manifestWorkSetLister implements the ManifestWorkSetLister interface.
type manifestWorkSetLister struct {
	indexer cache.Indexer
}

// NewManifestWorkSetLister returns a new ManifestWorkSetLister.
func NewManifestWorkSetLister(indexer cache.Indexer) ManifestWorkSetLister {
	return &manifestWorkSetLister{indexer: indexer}
}

// List lists all ManifestWorkSets in the indexer.
func (s *manifestWorkSetLister) List(selector labels.Selector) (ret []*v1alpha1.ManifestWorkSet, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.ManifestWorkSet))
	})
	return ret, err
}

// ManifestWorkSets returns an object that can list and get ManifestWorkSets.
func (s *manifestWorkSetLister) ManifestWorkSets(namespace string) ManifestWorkSetNamespaceLister {
	return manifestWorkSetNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// ManifestWorkSetNamespaceLister helps list and get ManifestWorkSets.
// All objects returned here must be treated as read-only.
type ManifestWorkSetNamespaceLister interface {
	// List lists all ManifestWorkSets in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.ManifestWorkSet, err error)
	// Get retrieves the ManifestWorkSet from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.ManifestWorkSet, error)
	ManifestWorkSetNamespaceListerExpansion
}

// manifestWorkSetNamespaceLister implements the ManifestWorkSetNamespaceLister
// interface.
type manifestWorkSetNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all ManifestWorkSets in the indexer for a given namespace.
func (s manifestWorkSetNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.ManifestWorkSet, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.ManifestWorkSet))
	})
	return ret, err
}

// Get retrieves the ManifestWorkSet from the indexer for a given namespace and name.
func (s manifestWorkSetNamespaceLister) Get(name string) (*v1alpha1.ManifestWorkSet, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("manifestworkset"), name)
	}
	return obj.(*v1alpha1.ManifestWorkSet), nil
}
