// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
	scheme "open-cluster-management.io/api/client/operator/clientset/versioned/scheme"
	v1 "open-cluster-management.io/api/operator/v1"
)

// ClusterManagersGetter has a method to return a ClusterManagerInterface.
// A group's client should implement this interface.
type ClusterManagersGetter interface {
	ClusterManagers() ClusterManagerInterface
}

// ClusterManagerInterface has methods to work with ClusterManager resources.
type ClusterManagerInterface interface {
	Create(ctx context.Context, clusterManager *v1.ClusterManager, opts metav1.CreateOptions) (*v1.ClusterManager, error)
	Update(ctx context.Context, clusterManager *v1.ClusterManager, opts metav1.UpdateOptions) (*v1.ClusterManager, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, clusterManager *v1.ClusterManager, opts metav1.UpdateOptions) (*v1.ClusterManager, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.ClusterManager, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.ClusterManagerList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.ClusterManager, err error)
	ClusterManagerExpansion
}

// clusterManagers implements ClusterManagerInterface
type clusterManagers struct {
	*gentype.ClientWithList[*v1.ClusterManager, *v1.ClusterManagerList]
}

// newClusterManagers returns a ClusterManagers
func newClusterManagers(c *OperatorV1Client) *clusterManagers {
	return &clusterManagers{
		gentype.NewClientWithList[*v1.ClusterManager, *v1.ClusterManagerList](
			"clustermanagers",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *v1.ClusterManager { return &v1.ClusterManager{} },
			func() *v1.ClusterManagerList { return &v1.ClusterManagerList{} }),
	}
}
