// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "open-cluster-management.io/api/work/v1alpha1"
)

// FakeManifestWorkSets implements ManifestWorkSetInterface
type FakeManifestWorkSets struct {
	Fake *FakeWorkV1alpha1
	ns   string
}

var manifestworksetsResource = schema.GroupVersionResource{Group: "work.open-cluster-management.io", Version: "v1alpha1", Resource: "manifestworksets"}

var manifestworksetsKind = schema.GroupVersionKind{Group: "work.open-cluster-management.io", Version: "v1alpha1", Kind: "ManifestWorkSet"}

// Get takes name of the manifestWorkSet, and returns the corresponding manifestWorkSet object, and an error if there is any.
func (c *FakeManifestWorkSets) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ManifestWorkSet, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(manifestworksetsResource, c.ns, name), &v1alpha1.ManifestWorkSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ManifestWorkSet), err
}

// List takes label and field selectors, and returns the list of ManifestWorkSets that match those selectors.
func (c *FakeManifestWorkSets) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ManifestWorkSetList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(manifestworksetsResource, manifestworksetsKind, c.ns, opts), &v1alpha1.ManifestWorkSetList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ManifestWorkSetList{ListMeta: obj.(*v1alpha1.ManifestWorkSetList).ListMeta}
	for _, item := range obj.(*v1alpha1.ManifestWorkSetList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested manifestWorkSets.
func (c *FakeManifestWorkSets) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(manifestworksetsResource, c.ns, opts))

}

// Create takes the representation of a manifestWorkSet and creates it.  Returns the server's representation of the manifestWorkSet, and an error, if there is any.
func (c *FakeManifestWorkSets) Create(ctx context.Context, manifestWorkSet *v1alpha1.ManifestWorkSet, opts v1.CreateOptions) (result *v1alpha1.ManifestWorkSet, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(manifestworksetsResource, c.ns, manifestWorkSet), &v1alpha1.ManifestWorkSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ManifestWorkSet), err
}

// Update takes the representation of a manifestWorkSet and updates it. Returns the server's representation of the manifestWorkSet, and an error, if there is any.
func (c *FakeManifestWorkSets) Update(ctx context.Context, manifestWorkSet *v1alpha1.ManifestWorkSet, opts v1.UpdateOptions) (result *v1alpha1.ManifestWorkSet, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(manifestworksetsResource, c.ns, manifestWorkSet), &v1alpha1.ManifestWorkSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ManifestWorkSet), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeManifestWorkSets) UpdateStatus(ctx context.Context, manifestWorkSet *v1alpha1.ManifestWorkSet, opts v1.UpdateOptions) (*v1alpha1.ManifestWorkSet, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(manifestworksetsResource, "status", c.ns, manifestWorkSet), &v1alpha1.ManifestWorkSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ManifestWorkSet), err
}

// Delete takes name of the manifestWorkSet and deletes it. Returns an error if one occurs.
func (c *FakeManifestWorkSets) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(manifestworksetsResource, c.ns, name, opts), &v1alpha1.ManifestWorkSet{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeManifestWorkSets) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(manifestworksetsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ManifestWorkSetList{})
	return err
}

// Patch applies the patch and returns the patched manifestWorkSet.
func (c *FakeManifestWorkSets) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ManifestWorkSet, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(manifestworksetsResource, c.ns, name, pt, data, subresources...), &v1alpha1.ManifestWorkSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ManifestWorkSet), err
}
