// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/listers"
	"k8s.io/client-go/tools/cache"
	v1 "open-cluster-management.io/api/work/v1"
)

// AppliedManifestWorkLister helps list AppliedManifestWorks.
// All objects returned here must be treated as read-only.
type AppliedManifestWorkLister interface {
	// List lists all AppliedManifestWorks in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.AppliedManifestWork, err error)
	// Get retrieves the AppliedManifestWork from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1.AppliedManifestWork, error)
	AppliedManifestWorkListerExpansion
}

// appliedManifestWorkLister implements the AppliedManifestWorkLister interface.
type appliedManifestWorkLister struct {
	listers.ResourceIndexer[*v1.AppliedManifestWork]
}

// NewAppliedManifestWorkLister returns a new AppliedManifestWorkLister.
func NewAppliedManifestWorkLister(indexer cache.Indexer) AppliedManifestWorkLister {
	return &appliedManifestWorkLister{listers.New[*v1.AppliedManifestWork](indexer, v1.Resource("appliedmanifestwork"))}
}
