// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	versioned "open-cluster-management.io/api/client/work/clientset/versioned"
	internalinterfaces "open-cluster-management.io/api/client/work/informers/externalversions/internalinterfaces"
	v1alpha1 "open-cluster-management.io/api/client/work/listers/work/v1alpha1"
	workv1alpha1 "open-cluster-management.io/api/work/v1alpha1"
)

// ManifestWorkSetInformer provides access to a shared informer and lister for
// ManifestWorkSets.
type ManifestWorkSetInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.ManifestWorkSetLister
}

type manifestWorkSetInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewManifestWorkSetInformer constructs a new informer for ManifestWorkSet type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewManifestWorkSetInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredManifestWorkSetInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredManifestWorkSetInformer constructs a new informer for ManifestWorkSet type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredManifestWorkSetInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.WorkV1alpha1().ManifestWorkSets(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.WorkV1alpha1().ManifestWorkSets(namespace).Watch(context.TODO(), options)
			},
		},
		&workv1alpha1.ManifestWorkSet{},
		resyncPeriod,
		indexers,
	)
}

func (f *manifestWorkSetInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredManifestWorkSetInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *manifestWorkSetInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&workv1alpha1.ManifestWorkSet{}, f.defaultInformer)
}

func (f *manifestWorkSetInformer) Lister() v1alpha1.ManifestWorkSetLister {
	return v1alpha1.NewManifestWorkSetLister(f.Informer().GetIndexer())
}
