package v1alpha1

// This file contains a collection of methods that can be used from go-restful to
// generate Swagger API documentation for its models. Please read this PR for more
// information on the implementation: https://github.com/emicklei/go-restful/pull/215
//
// TODOs are ignored from the parser (e.g. TODO(andronat):... || TODO:...) if and only if
// they are on one line! For multiple line or blocks that you want to ignore use ---.
// Any context after a --- is ignored.
//
// Those methods can be generated by using hack/update-swagger-docs.sh

// AUTO-GENERATED FUNCTIONS START HERE
var map_PlaceManifestWork = map[string]string{
	"":       "PlaceManifestWork is the Schema for the placementmanifestworks API",
	"spec":   "Spec reperesents the desired ManifestWork payload and Placement reference to be reconciled",
	"status": "Status represent the current status of Placing ManifestWork resources",
}

func (PlaceManifestWork) SwaggerDoc() map[string]string {
	return map_PlaceManifestWork
}

var map_PlaceManifestWorkList = map[string]string{
	"": "PlaceManifestWorkList contains a list of PlaceManifestWork",
}

func (PlaceManifestWorkList) SwaggerDoc() map[string]string {
	return map_PlaceManifestWorkList
}

var map_PlaceManifestWorkSpec = map[string]string{
	"":                 "PlaceManifestWorkSpec defines the desired state of PlaceManifestWork",
	"manifestWorkSpec": "ManifestWorkSpec is the ManifestWorkSpec that will be used to generate a per-cluster ManifestWork",
	"placementRef":     "PacementRef is the name of the Placement resource, from which a PlacementDecision will be found and used to distribute the ManifestWork",
}

func (PlaceManifestWorkSpec) SwaggerDoc() map[string]string {
	return map_PlaceManifestWorkSpec
}

var map_PlaceManifestWorkStatus = map[string]string{
	"":                   "PlaceManifestWorkStatus defines the observed state of PlaceManifestWork",
	"conditions":         "Conditions contains the different condition statuses for distrbution of ManifestWork resources Valid condition types are: 1. AppliedManifestWorks represents ManifestWorks have been distributed as per placement All, Partial, None, Problem 2. PlacementRefValid",
	"placedManifestWork": "ManifestWorkDelivery tracks each ManifestWork that was created, including that it was applied and its overall status",
	"summary":            "Summary that reflects all relevant ManifestWorks",
}

func (PlaceManifestWorkStatus) SwaggerDoc() map[string]string {
	return map_PlaceManifestWorkStatus
}

var map_PlacedManifestWork = map[string]string{
	"workRef":   "Work is an objectReference to the actual ManifestWork resource",
	"status":    "ManifestWorkStatus ManifestWorkStatus.Condition can be",
	"timestamp": "Timestamp is the time when the ManifestWork was last modified",
}

func (PlacedManifestWork) SwaggerDoc() map[string]string {
	return map_PlacedManifestWork
}

// AUTO-GENERATED FUNCTIONS END HERE
