// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/open-cluster-management/api/client/clusters/clientset/versioned/typed/clusters/v1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeClustersV1 struct {
	*testing.Fake
}

func (c *FakeClustersV1) SpokeClusters() v1.SpokeClusterInterface {
	return &FakeSpokeClusters{c}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeClustersV1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
