// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/listers"
	"k8s.io/client-go/tools/cache"
	v1alpha1 "open-cluster-management.io/api/cluster/v1alpha1"
)

// ClusterClaimLister helps list ClusterClaims.
// All objects returned here must be treated as read-only.
type ClusterClaimLister interface {
	// List lists all ClusterClaims in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.ClusterClaim, err error)
	// Get retrieves the ClusterClaim from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.ClusterClaim, error)
	ClusterClaimListerExpansion
}

// clusterClaimLister implements the ClusterClaimLister interface.
type clusterClaimLister struct {
	listers.ResourceIndexer[*v1alpha1.ClusterClaim]
}

// NewClusterClaimLister returns a new ClusterClaimLister.
func NewClusterClaimLister(indexer cache.Indexer) ClusterClaimLister {
	return &clusterClaimLister{listers.New[*v1alpha1.ClusterClaim](indexer, v1alpha1.Resource("clusterclaim"))}
}
