// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// ManagedClusterSetListerExpansion allows custom methods to be added to
// ManagedClusterSetLister.
type ManagedClusterSetListerExpansion interface{}
