// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// ManagedClusterClaimListerExpansion allows custom methods to be added to
// ManagedClusterClaimLister.
type ManagedClusterClaimListerExpansion interface{}

// ManagedClusterClaimNamespaceListerExpansion allows custom methods to be added to
// ManagedClusterClaimNamespaceLister.
type ManagedClusterClaimNamespaceListerExpansion interface{}

// MirroredManagedClusterListerExpansion allows custom methods to be added to
// MirroredManagedClusterLister.
type MirroredManagedClusterListerExpansion interface{}

// MirroredManagedClusterNamespaceListerExpansion allows custom methods to be added to
// MirroredManagedClusterNamespaceLister.
type MirroredManagedClusterNamespaceListerExpansion interface{}
